
default: main

main:
	gcc -lm prueba1.c -o prueba1 -Wall -O1
	gcc -lm prueba2_simple.c -o prueba2_simple -Wall -O1
	gcc -lm prueba2_doble.c -o prueba2_doble -Wall -O1
	gcc -lm prueba2_mixta.c -o prueba2_mixta -Wall -O1



